configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - ".moban.d"
  configuration: lml.yml
targets:
  - README.rst: README.rst.jj2
  - setup.py: setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "docs/source/index.rst": "docs/source/index.rst.jj2"
  - test.sh: test.sh.jj2
